// <auto-generated />
using System;
using Group8_Hobbies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Group8_Hobbies.Migrations
{
    [DbContext(typeof(HobbiesContextModel))]
    [Migration("20220423011912_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Group8_Hobbies.Models.AnimationModel", b =>
                {
                    b.Property<int>("AnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("PublisherCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int?>("WatchingYear")
                        .HasColumnType("int");

                    b.HasKey("AnimeId");

                    b.ToTable("Animations");

                    b.HasData(
                        new
                        {
                            AnimeId = 1,
                            Name = "Demon Slayer",
                            PublishYear = 2019,
                            PublisherCountry = "Japan",
                            PublisherName = "UFOTable",
                            Rate = 4,
                            WatchingYear = 2020
                        },
                        new
                        {
                            AnimeId = 2,
                            Name = "My NeighborTotoro",
                            PublishYear = 1988,
                            PublisherCountry = "Japan",
                            PublisherName = "Ghibli",
                            Rate = 5,
                            WatchingYear = 2007
                        },
                        new
                        {
                            AnimeId = 3,
                            Name = "White Cat Legend",
                            PublishYear = 2020,
                            PublisherCountry = "China",
                            PublisherName = "Nice Boat Animation Studio",
                            Rate = 4,
                            WatchingYear = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
