// <auto-generated />
using System;
using Group8_Hobbies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Group8_Hobbies.Migrations
{
    [DbContext(typeof(HobbiesContextModel))]
    [Migration("20220422171033_RunningModel")]
    partial class RunningModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Group8_Hobbies.Models.AnimationModel", b =>
                {
                    b.Property<int>("AnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherId1")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int?>("WatchingYear")
                        .HasColumnType("int");

                    b.HasKey("AnimeId");

                    b.HasIndex("PublisherId1");

                    b.ToTable("Animations");

                    b.HasData(
                        new
                        {
                            AnimeId = 1,
                            Name = "Demon Slayer",
                            PublishYear = 2019,
                            PublisherId = 1,
                            Rate = 4,
                            WatchingYear = 2020
                        },
                        new
                        {
                            AnimeId = 2,
                            Name = "My NeighborTotoro",
                            PublishYear = 1988,
                            PublisherId = 2,
                            Rate = 5,
                            WatchingYear = 2007
                        },
                        new
                        {
                            AnimeId = 3,
                            Name = "White Cat Legend",
                            PublishYear = 2020,
                            PublisherId = 3,
                            Rate = 4,
                            WatchingYear = 2020
                        });
                });

            modelBuilder.Entity("Group8_Hobbies.Models.PublishModel", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PublisherId");

                    b.ToTable("Publishes");

                    b.HasData(
                        new
                        {
                            PublisherId = 1,
                            Country = "Japan",
                            Name = "UFOTable"
                        },
                        new
                        {
                            PublisherId = 2,
                            Country = "Japan",
                            Name = "Ghibli"
                        },
                        new
                        {
                            PublisherId = 3,
                            Country = "China",
                            Name = "Nice Boat Animation Studio"
                        });
                });

            modelBuilder.Entity("Group8_Hobbies.Models.RunningModel", b =>
                {
                    b.Property<int>("RunningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RunningId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            RunningId = 1,
                            Date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 26.199999999999999,
                            Name = "Cincinnati Flying Pig",
                            Website = "https://flyingpigmarathon.com"
                        },
                        new
                        {
                            RunningId = 2,
                            Date = new DateTime(2022, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 3.1000000000000001,
                            Name = "Cleveland Turkey Trot",
                            Website = "https://www.turkeytrotcleveland.com"
                        },
                        new
                        {
                            RunningId = 3,
                            Date = new DateTime(2022, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 26.199999999999999,
                            Name = "Boston Marathon",
                            Website = "https://www.baa.org"
                        },
                        new
                        {
                            RunningId = 4,
                            Date = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 6.2000000000000002,
                            Name = "Bolder Boulder 10k",
                            Website = "https://www.bolderboulder.com"
                        },
                        new
                        {
                            RunningId = 5,
                            Date = new DateTime(2022, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 26.199999999999999,
                            Name = "Chicago Marathon",
                            Website = "https://www.chicagomarathon.com"
                        });
                });

            modelBuilder.Entity("Group8_Hobbies.Models.AnimationModel", b =>
                {
                    b.HasOne("Group8_Hobbies.Models.PublishModel", "Publish")
                        .WithMany()
                        .HasForeignKey("PublisherId1");
                });
#pragma warning restore 612, 618
        }
    }
}
